language:
  node_js
node_js:
  - 16.20
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll 
deploy:
  provider: pages
  skipt-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    repo: marcosvsilva/marcosvsilva.github.io
    branches:
      only:
        - master
after_deploy:
  - echo "Application Deployed! 🚀"
